# -*- coding: utf-8 -*-
"""5 tendencias mas vendidas en cada trimestre del año en Mercado Libre.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xjt9RzpnyBs_odqTj4ASySISb81hLP9r
"""

import requests
import pandas as pd

# Variables de configuración
token = 'N6opXnSFgJRcqNLwUY4kI3rzM8Fuxz4q' #'TU_TOKEN_DE_ACCESO'  # Reemplaza con tu propio token de acceso a la API de Mercado Libre

# Definir los rangos de fechas
rangos_fechas = [
    {'nombre': '1 de enero a 31 de marzo', 'fecha_desde': '2023-01-01', 'fecha_hasta': '2023-03-31'},
    {'nombre': '1 de abril a 30 de junio', 'fecha_desde': '2023-04-01', 'fecha_hasta': '2023-06-30'},
    {'nombre': '1 de julio a 30 de septiembre', 'fecha_desde': '2023-07-01', 'fecha_hasta': '2023-09-30'},
    {'nombre': '1 de octubre a 31 de diciembre', 'fecha_desde': '2023-10-01', 'fecha_hasta': '2023-12-31'}
]

# Obtener la lista de categorías de Mercado Libre
url_categorias = 'https://api.mercadolibre.com/sites/MLA/categories'
response = requests.get(url_categorias)
categorias = response.json()

# Obtener las categorías más vendidas por cada rango de fechas
categorias_mas_vendidas = []

for rango_fecha in rangos_fechas:
    fecha_desde = rango_fecha['fecha_desde']
    fecha_hasta = rango_fecha['fecha_hasta']
    nombre_rango = rango_fecha['nombre']
    
    for categoria in categorias:
        categoria_id = categoria['id']
        
        url_productos = f'https://api.mercadolibre.com/sites/MLA/search?category={categoria_id}&sort=sold_quantity_desc&limit=5&buying_mode=buy_it_now&currency=ARS&date_from={fecha_desde}T00:00:00.000-00:00&date_to={fecha_hasta}T23:59:59.999-00:00&access_token={token}'
        response = requests.get(url_productos)
        data = response.json()
        
        for producto in data['results']:
            detalles_categoria = {
                'Rango de Fechas': nombre_rango,
                'Categoría': categoria['name'],
                'Producto': producto['title'],
                'Precio': producto['price'],
                'Moneda': producto['currency_id'],
                'Condición': producto['condition'],
                'Cantidad Vendida': producto['sold_quantity']
            }
            categorias_mas_vendidas.append(detalles_categoria)

# Convertir los datos en un DataFrame de Pandas
df_categorias_mas_vendidas = pd.DataFrame(categorias_mas_vendidas)

# Guardar el resultado en un archivo CSV
df_categorias_mas_vendidas.to_csv('categorias_mas_vendidas.csv', index=False)

print("Archivo 'categorias_mas_vendidas.csv' generado exitosamente.")
