# -*- coding: utf-8 -*-
"""Productos más vendidos mercado libre.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18k3ou5w3BLbqCimK7bSYFWsGJ3IcHQ3T

# Top 15 de los productos más vendidos por año en Colombia

Productos 15 más vendidos de cada año de los últimos 3 años en MercadoLibre

Integrantes: 

*   Cristhian Mauricio Yara Pardo -20181020081
*   Laurent David Chaverra Córdoba - 20171020082
"""

import requests 
import json 
import pandas as pd


url = "https://api.mercadolibre.com/sites/MCO/categories"
response = requests.get(url)
if response.status_code == 200: 
    categorias_data = response.json() 
    for categoria in categorias_data: 
        categoria_id = categoria["id"] 
        categoria_nombre = categoria["name"] 
        print(f"Categoría {categoria_id}: {categoria_nombre}") 
else: print(f"Error al obtener la lista de categorías: {response.status_code}")


categorias = ["MCO1055", "MCO1648", "MCO1000", "MCO1039", "MCO1649"]
anios = [2018, 2019, 2020, 2021, 2022] 
resultados = []



for categoria in categorias: 
    url = f"https://api.mercadolibre.com/categories/{categoria}" 
    response = requests.get(url) 
    if response.status_code == 200: 
        categoria_data = response.json() 
        categoria_nombre = categoria_data.get("name") 
        print(f"Categoría {categoria}: {categoria_nombre}") 
    else: print(f"Error al obtener la categoría {categoria}: {response.status_code}")

def buscar_productos(categoria, pais, anio): 
    url = f"https://api.mercadolibre.com/sites/{pais}/search?category={categoria}&sold_quantity={anio}-01-01,{anio}-12-31&sort=sold_quantity_desc" 
    response = requests.get(url) 
    if response.status_code == 200: 
        return response.json() 
    else: return None

for categoria in categorias: 
    for anio in anios: 
        productos = buscar_productos(categoria, "MCO", anio) 
        if productos is not None: 
            for item in productos["results"][:15]:
                resultado = { "categoria": categoria, "anio": anio, "titulo": item["title"], "precio": item["price"], "moneda": item["currency_id"], "condicion": item["condition"], "ventas": item["sold_quantity"], "url": item["permalink"] }
                resultados.append(resultado)

df = pd.DataFrame(resultados)
df.to_csv("productos_mas_vendidos.csv", index=False, encoding='iso-8859-1')

#df = pd.read_csv("datos.csv")

print(df)